### ISSUE TITLE
FR: Supporting suggestion like Manjaro

### ISSUE THREAD

**Issue by HubKing** [jirutka/alpine-zsh-config#3]
Majaro enables suggestion (basically, showing a matching entry in history as a pale background text) like below by default. On Arch, I installed https://github.com/wszqkzqk/easy-zsh-config and it enabled it by default. I would like to have this feature, but after installing alpine-zsh-config and zsh-autosuggestions, it doesn't work, and I don't know how to make it work.

It would be nice if alpine-zsh-config enabled suggestion by default, or at least when the zsh-autosuggestions package is installed.

![image](https://github.com/jirutka/alpine-zsh-config/assets/10900489/79be5ca2-b878-4465-b3fa-9eb86bef6cd9)

**Comment by jirutka** [comment]
> but after installing alpine-zsh-config and zsh-autosuggestions, it doesn't work, and I don't know how to make it work.

It’s supposed to work exactly like this. If it doesn’t, then you probably have some problematic configuration that breaks autosuggestions or the plugin loading (maybe Oh My Zsh?).

Try it on a clean system, just `apk add zsh alpine-zsh-config zsh-autosuggestions`, then run `zsh`, and autosuggestions should work.
